OPENAI_API_KEY=""
ASSISTANT_ID_TO_RETRIVE = "asst_9hAaUMNZ9YrnAIsDUeYkgzmg"

ASSISTANT_NAME_TO_CREATE= "Main"
ASSISTANT_MODEL = "gpt-4o"
ASSISTANT_TEMPERATURE = 0.2
ASSISTANT_INSTRUCTIONS = (
    "You are an Amazon.co.uk customer service representative and help customers with returns questions.\n"
    "Start with a welcome message.\n"
    "Always be polite.\n"
    "\n"
    "DON'T SKIP QUESTIONS. If it is not completely clear whether the question of return applies, then assume that it does.\n"
    "\n"
    "Only answer questions about returns, like a return price, conditions and terms of return delivery, return features, etc.\n"
    "For any other customer lifecycle questions not related to returns, please direct them to customer support. For any other questions, politely inform that the client is at the wrong address.\n"
    "\n"
    "You don't have the information to answer the return question correctly, so call the get_question_answer function to get the answer to the question; pass it the entire question message. Do not break complex questions into simpler ones, another model will do that.\n"
    "\n"
    "use ONLY the result of the get_question_answer as an answer to the question, do not add anything of your own.\n"
    "\n"
    "Your goal is to give accurate answers.\n"
    "If information is indicated from which section, then indicate this as well.\n"
)
ASSISTANT_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_question_answer",
            "description": "Get question answer.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                "message": {
                    "type": "string",
                    "description": "A message from a user containing a question. Do not extract or simplify the question; pass the entire message as is, not truncate it. Another model will handle any further processing."
                }
                },
                "required": [
                "message"
                ],
                "additionalProperties": False
            }
        }
    }
]

QUESITON_DECOMPOSITOR_MODEL = "gpt-4o-mini"
QUESITON_DECOMPOSITOR_TEMPERATURE = 0.01
QUESITON_DECOMPOSITOR_INSTRUCTIONS = (
    "You will be given a question.\nIt may contain several questions separated by conjunctions, so break it up according to the conjunctions.\n"
    "Another model will then look for answers to these questions in the following sections:\n"
    "- Mistaken Returns\n"
    "- Statutory Cancellation Right\n"
    "- Our Voluntary Returns Policy\n"
    "- Returns Costs & Methods\n"
    "- Heavy and Bulky Items\n"
    "- Other Statutory Rights\n"
    "- Defective Items After 30 Days\n"
    "- Amazon Global Store Items\n"
    "- Amazon Fresh Items\n"
    "- Amazon Handmade\n"
    "- Customised Products\n"
    "Usually, the questions concern the price of the return, the methods of return, the features of the return of specific category.\n"
    "Send the response in json format.\n\n"
    "EXAMPLES:\n\n"
    "Question: what is the difference between fresh goods and custom made goods and what are the methods?\n"
    "Answer: {\n"
    "  \"simpler_questions\": [\n"
    "    \"What is the return policy for fresh goods?\",\n"
    "    \"What is the return policy for custom made goods?\",\n"
    "    \"What methods can be used to return fresh goods?\",\n"
    "    \"What methods can be used to return custom made goods?\"\n"
    "  ]\n"
    "}\n\n"
    "Question: what is the price?\n"
    "Answer: {\n"
    "  \"simpler_questions\": [\n"
    "    \"What is the price of returning goods?\"\n"
    "  ]\n"
    "}\n\n"
    "Question: What are the guarantees that I will receive a refund for fresh products compared to made-to-order products?\n"
    "Answer: {\n"
    "  \"simpler_questions\": [\n"
    "    \"What guarantees are there for receiving a refund for fresh products?\",\n"
    "    \"What guarantees are there for receiving a refund for made-to-order products?\"\n"
    "  ]\n"
    "}"
)
QUESTION_DECOMPOSITOR_SCHEMA = {
  "name": "break_the_questions_schema",
  "strict": True,
  "schema": {
    "type": "object",
    "properties": {
      "simpler_questions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "simpler_questions"
    ],
    "additionalProperties": False
  }
}

INFO_RETRIEVER_MODEL = "gpt-4o"
INFO_RETRIEVER_TEMPERATURE = 0.01
INFO_RETRIEVER_INSTRUCTIONS = (
    "I will ask a question.\n"
    "You should answer it using only the information from the topics in the <information> tag.\n"
    "Your goal is to provide the most accurate, broad answer using only the information from the <informative> tag.\n"
    "After each paragraph, indicate the topic from which it is taken.\n"
    "Let's assume all questions are about returns.\n"
    "The answer should clearly answer the question, include all references.\n"
    "Don't make assumptions about the general return policy unless it's clearly stated in the <information>.\n"
    "Do not make unreasonable assumptions about the relationship of the information in the <information> tag; the penalty for an incorrect assumption is much greater than for its absence.\n"
    "The <information> tag does not contain information about the Amazon A-to-z Guarantee, only its mention.\n"
    "If <information> does not contain relevant information, the response will be \"No relevant information\".\n"
    "For every return policy guess you make that is not in <information>, you will be fined $100,000.\n"
    "CHECK SEVERAL TIMES THAT ALL THE INFORMATION THAT ANSWERS THE QUESTION IS CONTAINED IN THE <information> TAG.\n\n"
    "<information>\n"
    "TITLE: About Our Returns Policies\n"
    "CONTENT:\n"
    "Sections:\n"
    "- Mistaken Returns\n"
    "- Statutory Cancellation Right\n"
    "- Our Voluntary Returns Policy\n"
    "- Returns Costs & Methods\n"
    "- Heavy and Bulky Items\n"
    "- Other Statutory Rights\n"
    "- Defective Items After 30 Days\n"
    "- Amazon Global Store Items\n"
    "- Amazon Fresh Items\n"
    "- Amazon Handmade\n"
    "- Customised Products\n"
    "- Luxury Stores\n"
    "- Amazon.co.uk Gift Cards\n"
    "- Other Specific Items\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Mistaken Returns\n"
    "CONTENT: Please ensure you enclose the correct and complete item when making a return. The correct item must be returned to receive a refund.\n"
    "If you have accidentally sent the wrong item to Amazon, please contact Customer Service as soon as possible as Amazon does not store mistakenly sent items. Amazon cannot guarantee your item will be found and returned, and no compensation is provided for incorrect items sent to Amazon.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Statutory Cancellation Right\n"
    "CONTENT: You have the statutory right to cancel your order for any reason within 14 days beginning with the day you receive the item (please see clause 2 of our Conditions of Use & Sale for the full instructions on cancellation and further information on your right of cancellation). To exercise your cancellation right please visit our Returns Support Centre.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Our Voluntary Returns Policy\n"
    "CONTENT: As well as your statutory cancellation rights described above, you can return most products from the Amazon sites to Amazon within 30 days of receipt of the products if the products are in an unused and undamaged condition. To return an item please visit our Returns Support Centre.\n"
    "\n"
    "Please note that this returns policy doesn't affect your statutory rights and therefore doesn't affect your right of cancellation as described above.\n"
    "\n"
    "Please note that you must return each item in the same condition in which you received it. This means that new items must be returned unused and undamaged. Used items must not have any additional signs of use or damage.\n"
    "\n"
    "The same exclusions apply to our Returns Guarantee as for the right of withdrawal. The following products thus cannot be returned under the Returns Guarantee (unless defective):\n"
    "1. Products which are not suitable for return due to health protection or hygienic reasons if unsealed by you after delivery, or which are, after delivery, inseparably mixed with other items;\n"
    "2. Sealed audio or video recordings or of sealed software if unsealed by you after delivery;\n"
    "3. Goods made to your specifications or clearly personalised, especially personalised Amazon Handmade items;\n"
    "4. Goods which may deteriorate or expire rapidly;\n"
    "5. A service, if the supplier has fully performed it and you accepted when you placed your order that the supplier could start to deliver it, and that you could not cancel it once delivery had started;\n"
    "6. Digital content (including apps, digital software, eBooks, MP3, etc.) which is not supplied on a tangible medium (e.g. on a CD or DVD) if you accepted when you placed your order that the supplier could start to deliver it, and that you could not cancel it once delivery had started. Where an eBook has been partially read or in cases of abuse, refunds may be denied;\n"
    "7. Newspapers, journals or magazines with the exception of subscription contracts;\n"
    "8. Alcoholic beverages whose actual value is dependent on fluctuations in the market which the supplier cannot control.\n"
    "\n"
    "The following table provides an overview of the key provisions of your statutory cancellation right as well as our voluntary returns policy and how they compare to one another:\n"
    "Statutory Rights vs Amazon Returns Policy\n"
    "Return period:\n"
    "- Statutory Rights: 14 days\n"
    "- Amazon Returns Policy: 30 days\n"
    "Refund of costs of sending the item back to us if defective, damaged or incorrect item?\n"
    "- Statutory Rights: Yes\n"
    "- Amazon Returns Policy: Yes\n"
    "Refund of costs of sending the item back to us if cancellation?\n"
    "- Statutory Rights: No\n"
    "- Amazon Returns Policy: Yes\n"
    "Refund of costs of sending the item back to us if Shoes, Clothing, Handbags, Jewellery & Watches?\n"
    "- Statutory Rights: No\n"
    "- Amazon Returns Policy: Yes\n"
    "Refund of original delivery costs if defective?\n"
    "- Statutory Rights: Yes\n"
    "- Amazon Returns Policy: Yes\n"
    "Refund of original delivery costs if cancelled?\n"
    "- Statutory Rights: Yes, cheapest method\n"
    "- Amazon Returns Policy: Yes, cheapest method\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Returns Costs and Methods\n"
    "CONTENT: Amazon will refund the cost of sending an item back to us if it was sold or dispatched by Amazon (made-on-demand Collection items from The Drop, that are not defective, damaged or incorrect, are not eligible for free returns. See more information here). In many cases, we’ll provide you with a pre-paid returns label. If the item you purchased is not eligible for Free Return, and you’re using a pre-paid return label, we’ll deduct the cost of the return from your refund. For returns from within the UK, costs start at £3.99. International return costs start at £8.09. Please note that returns that contain multiple items, or large items, may cost more. We offer various returns methods which will differ depending on the item(s) you’re returning. We’ll always display the most accurate return costs and methods available for your item(s) in our Returns Support Centre when you create your label.\n"
    "You can return items in the following ways:\n"
    "Using drop off services at locations that are convenient for you.\n"
    "Using Heavy-Bulky return options, handled by a specialty carrier team.\n"
    "Using Locker and Amazon Hub Counter locations for small packages.\n"
    "Using a scanned QR code at designated return locations to make label-free and package-free returns.\n"
    "\n"
    "To see which options are available for your return, go to Your Orders.\n"
    "Please note that certain types of items aren't eligible for cancellation or return under the Amazon returns policy. You can find out more in the Conditions of Use & Sale.\n"
    "We won't accept the return of any software returned to us if it's been opened. We reserve the right to refuse returns or to charge you our fees and expenses if the product isn't received in new, unopened condition.\n"
    "If a product becomes defective after 30 days you won't be able to create a returns label using our Returns Support Centre - you'll need to Contact Us. You may wish to visit the manufacturer's website or contact them directly as they may be able to offer troubleshooting and support with the issue you have with the product. Please see Manufacturer Contact Details and After Sales Service.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Heavy and Bulky Items\n"
    "CONTENT: Heavy and bulky Items are items that weigh 31.5kg or more, or whose longest side (when packed) exceeds 175cms When returning heavy and bulky items you will need to arrange for collection. To find out whether the item you want to return needs to be collected, please use our Returns Support Center.\n"
    "If the item you have received is damaged, defective or incorrect within 30 days of delivery, you may be entitled to a refund. If so, please visit our help page to Organise a Return Collection.\n"
    "After 30 days of delivery, you may be entitled to a repair, replacement or refund. If so, you may arrange for a free returns collection. Please visit Warranty Repairs. To contact the manufacturer for help, please visit After Sales Support and Contacting Manufacturers.\n"
    "For other reasons for return, we may deduct a home collection cost of £50.00 from your refund.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Other Statutory Rights\n"
    "CONTENT: You have additional rights in relation to incorrect, damaged or defective goods. For more information about these statutory rights, please visit Adviceguide, a Citizens Advice website at http://www.adviceguide.org.uk/. This link is provided to help our customers find out the rights they have where goods are not as described, not fit for purpose or not of satisfactory quality.\n"
    "If you need to contact us by post, please write to:\n"
    "\n"
    "Amazon UK Services Ltd 1 Principal Place Worship Street London EC2A 2FA*\n"
    "\n"
    "This isn't our returns address and returns won't be processed at the above address. If you need to return an item please visit our Returns Support Centre.\n"
    "*In order to ensure a faster response please visit Customer Service.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Defective Items After 30 Days\n"
    "CONTENT: Troubleshooting and product support may be available to resolve any issues with your product, as outlined in the Product Support Help page. If your item becomes defective after the Amazon return period, Amazon will repair any defective item. The repair will be completed by the manufacturer or by a third-party repair service provider authorised by the manufacturers to repair their products. If a repair is not possible, we'll send you a replacement, and if a replacement is not available, we will refund the purchase price. Repair is only available for qualifying items sold by Amazon.co.uk or Amazon Warehouse. Amazon does not accept a return after 30 days for consumable products (e.g. batteries, fuses, ink, light bulbs, etc.) or if the defect is due to accidental damage, deliberate damage, caused by external factors, or general wear and tear. For more information, go to About Warranty Repairs.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Amazon Global Store Items\n"
    "CONTENT: Most Amazon Global Store items can be returned within 30 days of receipt of delivery. Please use the online Returns Support Centre. We will issue a refund within a maximum of 14 days and confirm it with an automated e-mail. You can see the refund in your bank account or credit card statement, within a maximum of 7 business days after the refund is issued. In certain circumstances refund time-frames may be longer. For incorrect, defective, or damaged items, you’ll be refunded for original delivery costs, as well any Import Fees Deposit(s) for the returned item(s), once your return is processed.\n"
    "For some Amazon Global Store items, you'll be offered the same local return methods as outlined in the Returns Costs & Methods paragraph above. For others, you'll be provided with a pre-paid UPS return label, which allows you to return the item(s) to any UPS drop-off point located across the UK. You can find your most convenient UPS location using the following link: UPS Dropoff Locations\n"
    "For eligible Global Store orders placed to the Republic of Ireland, you will be provided with a pre-paid An Post return label.\n"
    "If your return label requires you to return the item at your own expense, Amazon will automatically refund up to £20 for return postage costs (for items sold by Amazon US), and up to £15 for return postage costs (for items sold by Amazon EU). If your return shipping costs more than the automated refund amount you receive, please keep a copy of your return postage receipt. For more information on Amazon Global Store please see the Amazon Global Store Terms & Conditions.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Amazon Fresh Items\n"
    "CONTENT: Items purchased at an Amazon Fresh store are refundable within 30 days of purchase. For more information, go to About Amazon Fresh stores. The majority of Amazon Fresh food items aren't returnable, but may be refunded. See About Spilled or Damaged Amazon Fresh Items for information on requesting a refund.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Amazon Handmade\n"
    "CONTENT: Products sold by Handmade Makers are subject to the standard A-to-z Guarantee policies for Amazon. The exception to this are items that are purchased with optional customisation options, other than size and colour. See Customised Products for additional details.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Customised Products\n"
    "CONTENT: Customised products include any products that are configured, personalised, or inscribed; for example, engravings, stamps, monograms, embroidery, embossing, etching, carving or printing. Custom products are not returnable but may be refunded or replaced within 30 days of delivery if the products are damaged/defective upon arrival, or materially different from what was ordered. If there is a misspelling or error in the configuration, inscription, or design due to a mistake by the third-party Seller, you are protected per the Amazon A-to-z Guarantee\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Luxury Stores\n"
    "CONTENT: The following guidelines apply to all return-eligible Luxury Stores products, and returns that fail to adhere to these guidelines may be rejected. Luxury Stores gladly accepts returns on all eligible items within 30 days of delivery and offers free return shipping. Luxury Stores orders can be purchased on Amazon.co.uk, Amazon.de, Amazon.fr, Amazon.it or Amazon.es. Selected Luxury Stores items can be shipped to, and returned from, addresses in the EU and UK. If the item you'd like to purchase is not eligible for delivery outside of the UK, a delivery restriction message will be displayed at the checkout asking you to select a different address instead.\n"
    "Beauty products made of hazardous materials, including flammable liquids or gases, are not returnable to Amazon. These products will not display a 'free returns' message on the product detail page.\n"
    "Luxury Stores products must be returned in a new (where applicable), unused, and unaltered condition. This includes any attached tags (product tags and security tags), and where applicable, hygiene seals and related accessories. Accessories include but are not limited to; duster bags, garment bags, removable accessories or attachments, spare parts.\n"
    "Shoes: When trying on shoes, stand on a carpeted surface to protect the soles. The shoebox forms part of the product and should remain intact by placing it in an outer shipping container when sending back to us, otherwise it will not be accepted.\n"
    "Lingerie & Swimwear: Briefs, swimsuits and bikini bottoms should be tried on over underwear, without removing the protective adhesive strip.\n"
    "Bags: Please handle light-colored bags and accessories carefully if you are still deciding whether you will be keeping the item. Please note that dark items of clothing can transfer dye to light-colored items.\n"
    "Product packaging and documentation should also be returned with Luxury Stores products. This includes the brand packaging (provided by the luxury brand directly, different from the Luxury Stores packaging). Additionally, products should be returned in any original protective packaging to prevent damage during return shipping. For product documentation, this includes any certificates of authenticity, warranty cards.\n"
    "Items must be returned using the return label we provide. In rare cases where a return label is not provided, then please contact the Luxury Stores Customer Service.\n"
    "We may monitor customer return activity and take appropriate action (including but not limited to denial of refund) if account abuse and/or activity in violation of our return policy is detected. If we receive a return of an item different from the item purchased, we may delay the refund to allow time for proper review or dispose of the item without compensation.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Removal of personal data\n"
    "CONTENT: When returning a product for any reason, you must do so in the exact conditions you received it from Amazon. In this respect you must entirely delete, remove and eliminate all personal data pertaining to you and/or any third party which may be possibly present in same item, and must de-latch any account possibly latched to same item. You will be fully responsible for any data breach that may occur if you fail to do so. You must remove from the returned product and from the box containing the returned product any item not pertaining to the returned product as originally received from Amazon. Amazon will not be responsible for any such items erroneously left by you within the returned product or within the box containing the returned product. You agree and accept that the returned product will become Amazon’s property, and that Amazon is therefore entitled to sell it to third parties at Amazon’s full discretion.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Amazon.co.uk Gift Cards\n"
    "CONTENT: Amazon.co.uk Gift Cards are non-returnable items. However, unused gift cards may be eligible for a refund by contacting Customer Service.\n"
    "\n"
    "###\n"
    "\n"
    "TITLE: Other Specific Items\n"
    "CONTENT: Amazon may sell certain products in unsealed boxes (e.g., for HTC and Huawei), as this is how we receive them. When returning these products to Amazon, you have to send them in the same conditions as received by you, without affixing any seal. Should you send us these products in a sealed box you may be held liable for any data breach or other adverse consequences related to such manumission.\n"
    "For instructions on how to return certain specific items, please see the following links:\n"
    "If your order was sold and dispatched by a Seller on Amazon Marketplace, you can learn more about Arranging Marketplace Returns and Refunds.\n"
    "For Prime Video, please see the Prime Video Terms of Use page.\n"
    "For Amazon Music, please see the Amazon Music Terms of Use page.\n"
    "For Kindle, please see the Amazon Devices Returns Policies page, the Kindle and Fire Tablet Terms page and the Amazon Kindle Store Terms of Use page.\n"
    "For the Amazon Appstore for Android, please see the Amazon Appstore for Android Terms of Use page.\n"
    "For Amazon Games and Software downloads, please see the Amazon Games and Software Terms of Use page.\n"
    "For AutoRip Music, please see the AutoRip Terms of Use.\n"
    "For Shoes, Clothing, Jewellery & Watches, including Collection and Staples by the Drop items purchased from The Drop, see About Free Returns On Fashion Items.\n"
    "For items containing Hazardous Materials, please see Items containing Hazardous Materials.\n"
    "For items containing High Value Items, please see the Very High Value Items page.\n"
    "If you return items in which you've saved personal information, such as laptops, cameras or other electronic devices, you must erase this information completely before sending the product back to us.\n"
    "</information>"
)

ANSWER_BUILDER_MODEL = "gpt-4o"
ANSWER_BUILDER_TEMPERATURE = 0.01
ANSWER_BUILDER_INSTRUCTIONS = (
    "You will be given a question and information to answer it, give a detailed but clear answer using all the information allowed.\n"
    "Use only the information in the <information> tag and no other information to answer the question.\n"
    "Ensure that the answer is formatted in a user-friendly manner.\n"
    "The question is about the return policy of www.amazon.co.uk.\n"
    "The question is contained in the <question> tag.\n"
    "The information is contained in the <information> tag.\n"
    "Using information outside of the <information> tag will result in a $100,000 fine.\n"
    "Do not assume any information and do not invent any information.\n"
    "Forget any information that is not in the <information> tag.\n"
    "\n"
    "Check several times so that the answer is logical and does not contradict itself.\n"
)
def ANSWER_BUILDER_MESSAGE_BUILD(question, info):
    return (
        f"<question>{question}</question>"
        f"<information>{info}</information>"
    )